### ISSUE TITLE
Letters possibly out of order?

### ISSUE THREAD

**Issue by tigersdontmeow** [eleriaqueen/pso-highres-hud-font-resource-pack#1]
Hey, awesome work on this. I'm seeing an issue where characters seem to be consistently getting replaced by other characters. For example lower case g shows as capital W, x shows as a number 7, etc.

![image](https://user-images.githubusercontent.com/90012423/131933714-48959a3b-52b8-4fb7-8ffe-f2676adaccf4.png)

I'm running Dolphin 5.0-15103, but I also tried this with the stated Dolphin 5.0-14445 and got the same behavior. I'm using this on PSO Plus (v1.02)

I also tried the 'compat' mode, not sure what that one is for. Otherwise this is great. Just thought you might like to know/wondering if you were seeing the same thing or not. Thanks!

Edit: noting this is PSOGC.HR.HUD.Font.v0.4.0a

**Comment by eleriaqueen** [comment]
Oh this is weird, I didn't noticed such behavior when I did tests...
Gonna look into this.
Thing is, letters can't really be out of order, something else must be up...

**Comment by eleriaqueen** [comment]
I did a quick test and I'm not seeing the issue you have on Dolphin 14445 with PSO PAL nor PLUS.

**Comment by eleriaqueen** [comment]
Okay I'm seeing issues in some menus, first my HighRes font is missing the ":" (colon) but that seems to be the least of the issues.
"->" seems to be replaced by "W" ... what the hell...

Oh no ! I guess SEGA done fluffed-up, some menus seem coded so that it takes the "font file" and swaps a few letters with symbols or even swap letter placement... Why oh why SEGA...
They did the exact same thing with Phantasy Star Portable 2 / Infinity, in that game it destroyed any hope of having a high resolution font actually work in game. (I'm working on a HighRes UI for that game)

It might actually be impossible to fix.

You might want to delete the font file at "Documents\Dolphin Emulator\Load\Textures\GPO\"
![Capture](https://user-images.githubusercontent.com/4411178/131976768-4d1de574-f9e3-466d-92b4-24379438fe31.PNG)

It'll restore the original (blurry) font.
Sorry, I thought the trick I used was perfect, it clearly wasn't.

**Comment by tigersdontmeow** [comment]
I removed that and it did fix the issue. At least we get to keep the pretty damage/XP/hp/tp numbers and names. :)
